export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOG_OUT = "LOG_OUT";
export const HOME_VIDEOS_SUCCESS = "HOME_VIDEOS_SUCCESS";
export const HOME_VIDEOS_FAIL = "HOME_VIDEOS_FAIL";
export const HOME_VIDEOS_REQUEST = "HOME_VIDEOS_REQUEST";

export const SEARCHED_VIDEO_REQUEST = "SEARCHED_VIDEO_REQUEST";
export const SEARCHED_VIDEO_SUCCESS = "SEARCHED_VIDEO_SUCCESS";
export const SEARCHED_VIDEO_FAIL = "SEARCHED_VIDEO_FAIL";
